- name: git
  sudo: yes
  apt: pkg=git state=present

- name: update system
  sudo: yes
  apt: update_cache=yes upgrade=dist

- name: checkout devstack
  git: repo={{devstack_repo}} dest=/home/vagrant/devstack version={{devstack_branch}} accept_hostkey=yes

- name: setup manila localrc
  template: src=localrc.j2 dest=/home/vagrant/devstack/localrc

- name: stack.sh
  shell: /home/vagrant/devstack/stack.sh 2>&1 > /home/vagrant/stacklog

- name: copy post_install file
  copy: src=post_install.sh dest=/home/vagrant

- name: setting up post_install
  shell: bash post_install.sh

- name: set localrc to offline
  lineinfile: dest=/home/vagrant/devstack/localrc regexp="^OFFLINE=" line="OFFLINE=True"
